### ISSUE TITLE
fail to build

### ISSUE THREAD

**Issue by soul0knight** [uos/rmcl#1] opened 2022-11-08 08:53 UTC
Hello, thanks for your excellent work.
When I catkin_make this project, I got the following error.
![image](https://user-images.githubusercontent.com/42534001/200513931-0fd975b9-14d3-46dd-ab97-4b33cd392dd9.png)
So I made the following changes to the cmakelist file.
![image](https://user-images.githubusercontent.com/42534001/200514391-ee6237b0-eec4-466e-87f7-1f446f64da1e.png)
But I got the following error.
![image](https://user-images.githubusercontent.com/42534001/200515299-534c32f0-b453-4bed-86b5-24dc1cf61a4a.png)

Here is my software environment.
Ubuntu version: 18.04
Ros version: melodic
embree 3.13.5
nvidia optix 7.3
assimp 5.1.0

I think the installation of rmagine is OK.
![image](https://user-images.githubusercontent.com/42534001/200518763-06dddfac-a906-4eae-b7dc-728ff8c2d58a.png)
![image](https://user-images.githubusercontent.com/42534001/200518925-a57ddcb0-e302-4341-a9e7-e9a0a228b91c.png)

**Comment by aock** [comment] 2022-11-09 22:06
Hi soul0knight,

for development I used Ubuntu 20, ROS-noetic and Assimp 5.0.1 since you can install it under Ubuntu 20 via apt. With this setup I always installed Rmagine in a global manner without changing the `CMAKE_INSTALL_PREFIX`. Unfortunately I cannot test the software with Ubuntu 18, but I managed to reproduce the errors with my Ubuntu 20. What I did:

1. Download Assimp 5.2.0 from Github. Build it and install it in a custom folder by changing the `CMAKE_INSTALL_PREFIX`
2. Same with latest Rmagine version.
3. catkin_make in ROS-Workspace including rmcl

Then i got the same errors as you. I discovered there are essentially two problems: Assimp changed the contents of the `assimp_LIBRARIES` variable from the actual library (5.0.1) to a target named `assimp::assimp` (5.2.0). The second problem was actually a Bug in the generation of the find_package script of Rmagine. The include folder was a relative path "include" instead of a absolute longer path. I fixed both with backwards compatibility. I would be happy if you could test this before I merge it into the main branch.

To do that you have to checkout the develop branch of [Rmagine](https://github.com/uos/rmagine) and recompile it again. In my tests I also added the custom library paths of Rmagine and Assimp to some environment variables:

```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/amock/software/rmagine/install/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/amock/software/assimp/install/lib
export LIBRARY_PATH=$LIBRARY_PATH:/home/amock/software/rmagine/install/lib
export LIBRARY_PATH=$LIBRARY_PATH:/home/amock/software/assimp/install/lib
```

Bit I am not sure if this is really required. After that proceed as you did before, but reset the rmcl CMakeLists first and only doing the following Rmagine related path changes instead:

```cmake
set(rmagine_DIR "/home/amock/software/rmagine/install/lib/cmake/rmagine")
```

You could also instead go to the build-folder of your workspace, enter `ccmake .`, and change the variable there. After that it compiles successfully again for me.


Greetings
Alex

**Comment by soul0knight** [comment] 2022-11-10 07:06
Thanks for your reply.
I clone the [project](https://github.com/uos/rmagine/tree/develop) from the develop branch. And I added the library path of Rmagine to the environment variable:

> export LIBRARY_PATH=$LIBRARY_PATH:/home/sun/SLAM_My/Rmagine/rmagine-develop/install/lib

Then add rmagine_DIR to cmakelist file in RMCL and catkin_make:

> set(rmagine_DIR "/home/sun/SLAM_My/Rmagine/rmagine-develop/install/lib/cmake/rmagine")

Although an error is reported, I don't think it's a problem with Rmagine.
![image](https://user-images.githubusercontent.com/42534001/201020553-296b2116-765e-4ba9-8ed9-ef6ce6bc9399.png)
The error indicating that the include file for embree could not be found, and I add these codes to the cmakelist file in RMCL:

> set(TBB_DIR "/home/sun/TBB_INSTALL/oneTBB/install/lib/cmake/TBB")
> find_package(TBB REQUIRED)
> set(embree_DIR "/home/sun/SLAM_My/Rmagine/3rdparty/embree-3.13.5/install/lib/cmake/embree-3.13.5")
> find_package(embree 3 REQUIRED)

After that it compiles successfully for me.
However, I don't currently have the data to test this, can you share with me an available meshfile, such as the one you mention in the launch file? If so, thank you very much!

Greetings
Junshun

**Comment by aock** [comment] 2022-11-10 08:54
Hi Junshun,

very well, then I merge it into the main branch, create a new release, and close this issue.  

I also thought about providing some example data to get a fast start with rmcl. However, it is not related to this issue. Please contact me at amock@uos.de. Thanks for your help!

-- Alex

**Closed by aock** 2022-11-10 08:54 UTC
